#+STARTUP: showall

I know next to nothing about scrum. I know only that I want to stay
away from it as much as I can. So here I am writing a project to help
us (eventually) scrum.

* Requirements

  It ...

  - ... is written in Common Lisp. Specifically it is written for ~sbcl~.
  - ... uses Mozilla Persona for authentication and ~drakma~ to
    communicate with Mozilla Persona.
  - ... uses Gravatar for avatars and ~md5~ to get the Gravatar avatars
  - ... uses the ~restas~ web framework.
  - ... uses PostgreSQL as a database and ~postmodern~ to talk to
    the database.
  - ... uses ~cl-json~ to generate JSON
  - ... uses ~closure-template~ for the few templates it has.
  - ... uses bootstrap for layout.
  - ... uses jQuery for some of the JavaScript functionality.
  - ... uses Font Awesome for icons.
  - ... and uses React for the UI.

  In other words you need to have the following software installed:

  - [[http://sbcl.org][SBCL]]
  - [[http://postgresql.org][PostgreSQL]]

  And the following Common Lisp packages:

  - ~drakma~
  - ~md5~
  - ~restas~
  - ~postmodern~
  - ~cl-json~
  - ~closure-template~

  ... which should all be available through [[http://quicklisp.org][Quicklisp]]. And the
  following JavaScript and/or CSS frameworks and libraries are pulled
  from CDN's by default, but may be customized to load from anywhere
  you wish:

  - [[http://twitter.github.io/bootstrap][Bootstrap]]
  - [[http://jquery.com][jQuery]]
  - [[http://fontawesome.io][Font Awesome]]
  - [[http://facebook.github.io/react][React]]

* License

  scrumli is free software: you can redistribute it and/or modify it
  under the terms of the GNU Affero General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.

  scrumli is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public
  License along with scrumli.  If not, see
  [[http://www.gnu.org/licenses/]].

  See [[http://code.ryuslash.org/cgit.cgi/scrumli/tree/COPYING][COPYING]] for more information.
